/**
 * AI Marketing Analysis — ready-made (non-chat) performance marketing report
 * generated by the AI engine for the Intelligence Hub.
 *
 * The report is produced as a structured object so the frontend can render
 * prose sections, charts, spend recommendations and target comparisons
 * without any conversational interface.
 */

export type AIAnalysisStatus = 'success' | 'degraded';

export type AIAnalysisChartType =
    | 'vertical_bar'
    | 'horizontal_bar'
    | 'line'
    | 'donut'
    | 'pie'
    | 'bubble'
    | 'table';

export interface IAIMarketingAnalysisChart {
    chartType: AIAnalysisChartType;
    title: string;
    /** Chart data — format depends on chartType (see chart component props). */
    data: any;
}

export interface IAIMarketingSpendRecommendation {
    entity: string;
    entityType: 'channel' | 'campaign' | 'ad_set' | 'ad_group';
    action: 'increase_budget' | 'decrease_budget' | 'maintain' | 'pause';
    currentSpend: number | null;
    suggestedAllocation: string | null;
    rationale: string;
}

export interface IAIMarketingSection {
    heading: string;
    content: string;
    recommendations?: string[];
}

export interface IAIMarketingReport {
    title: string;
    executiveSummary: string;
    sections: IAIMarketingSection[];
    spendRecommendations: IAIMarketingSpendRecommendation[];
    risksAndAlerts: string[];
    nextSteps: string[];
}

export interface IAIMarketingTargetRow {
    entity: string;
    level: 'campaign' | 'ad_set';
    channel: string | null;
    spend: number;
    conversions: number;
    conversionsTarget: number | null;
    roas: number | null;
    roasTarget: number | null;
    cpa: number | null;
    cpaTarget: number | null;
    status: 'on-target' | 'above-target' | 'below-target' | 'no-target';
}

export interface IAIMarketingSourceSummary {
    hasMarketingData: boolean;
    campaignCount: number;
    targetCount: number;
    alertCount: number;
    totalSpend: number;
    totalConversions: number;
    overallRoas: number | null;
    overallCpl: number | null;
}

export type AIAnalysisScopeType = 'project' | 'campaign' | 'ad_set';

export interface IAIMarketingAnalysisScope {
    type: AIAnalysisScopeType;
    campaignId?: string | null;
    campaignName?: string | null;
    channel?: string | null;
    adSetName?: string | null;
}

export interface IAIMarketingAdSetScope {
    name: string;
    spend: number;
    conversions: number;
    roas: number | null;
    cpl: number | null;
    status: string;
}

export interface IAIMarketingAnalysisResponse {
    aiStatus: AIAnalysisStatus;
    fromCache: boolean;
    generatedAt: string;
    dateRange: { start: string; end: string };
    report: IAIMarketingReport;
    charts: {
        channelSpend: IAIMarketingAnalysisChart;
        channelRoas: IAIMarketingAnalysisChart;
        spendAllocation: IAIMarketingAnalysisChart;
        weeklyTrend: IAIMarketingAnalysisChart;
        dailySpend: IAIMarketingAnalysisChart;
        topCampaigns: IAIMarketingAnalysisChart;
        adSetPerformance: IAIMarketingAnalysisChart;
        spendByAge: IAIMarketingAnalysisChart;
        spendByGender: IAIMarketingAnalysisChart;
        spendByDevice: IAIMarketingAnalysisChart;
        spendByPlatform: IAIMarketingAnalysisChart;
    };
    targetComparison: IAIMarketingTargetRow[];
    sourceSummary: IAIMarketingSourceSummary;
    /** What this report covers (project / campaign / single ad set). */
    scope: IAIMarketingAnalysisScope;
    /** Ad groups / ad sets available in the campaign (for the scope selector). */
    adSetScopes: IAIMarketingAdSetScope[];
}

/**
 * Raw structured JSON contract returned by Gemini for the marketing analysis.
 * Field names are snake_case because they are authored by the model.
 */
export interface IMarketingAnalysisAIResponse {
    title: string;
    executive_summary: string;
    sections: Array<{
        heading: string;
        content: string;
        recommendations?: string[];
    }>;
    spend_recommendations: Array<{
        entity: string;
        entity_type: 'channel' | 'campaign' | 'ad_set' | 'ad_group';
        action: 'increase_budget' | 'decrease_budget' | 'maintain' | 'pause';
        current_spend?: number | null;
        suggested_allocation?: string | null;
        rationale: string;
    }>;
    risks_and_alerts: string[];
    next_steps: string[];
}
